FROM python:3.9-slim
LABEL fragarie 'fragarie@yandex.com'

RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0 \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
RUN python3 -m venv /faceapp-api/venv
COPY requirements.txt /faceapp-api/
RUN /faceapp-api/venv/bin/pip3 install -r /faceapp-api/requirements.txt
COPY . /faceapp-api/
WORKDIR /faceapp-api

ENTRYPOINT ["/faceapp-api/venv/bin/python3", "faceapp-api.py"]